[default_config]
version = "0.9.0"
assembler = "gas"
instruction_set = "arm"

[default_config.opts]
compiler = "arm-none-eabi-as"
compile_flags_txt = [
	"-g",
	"-Wall",
	"-T",
	"baremetal.ld"
]
diagnostics = true
default_diagnostics = false
